#Practice Assignment 7.1
Q1) Vectorize the given text data using countvectorizer() object. What is the shape of text_data after vectorization?

In [ ]:
import warnings
warnings.filterwarnings("ignore")

In [ ]:
text_data=['A metaverse is a network of 3D virtual worlds focused on social connection.',
           'In futurism and science fiction, the term is often described as a hypothetical iteration of the Internet as a single', 
           'universal virtual world that is facilitated by the use of virtual and augmented reality headsets.',
           'The term "metaverse" has its origins  the 1992 science fiction novel Snow Crash as a portmanteau of "meta" and "universe."',
           'Various metaverses have been developed for popular use such as virtual world platforms like Second Life.',
           'Some metaverse iterations involve integration between virtual and physical spaces and virtual economies',
           'often including a significant interest in advancing virtual reality technology.', 
           'The term has seen considerable use as a buzzword for public relations purposes to exaggerate development progress for various related technologies and projects.[10] Information privacy and user addiction are concerns within metaverses',
           'stemming from challenges facing the social media and video game industries as a whole.']

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cnt = CountVectorizer()
Text_Count = cnt.fit_transform(text_data)
Text_Count.shape

(9, 99)

In [ ]:
print(Text_Count)

  (0, 51)	1
  (0, 43)	1
  (0, 53)	1
  (0, 55)	1
  (0, 2)	1
  (0, 94)	1
  (0, 98)	1
  (0, 26)	1
  (0, 57)	1
  (0, 77)	1
  (0, 15)	1
  (1, 43)	1
  (1, 55)	1
  (1, 35)	1
  (1, 29)	1
  (1, 5)	1
  (1, 71)	1
  (1, 25)	1
  (1, 86)	2
  (1, 84)	1
  (1, 56)	1
  (1, 18)	1
  (1, 7)	2
  (1, 34)	1
  (1, 44)	1
  :	:
  (7, 64)	1
  (7, 69)	1
  (7, 82)	1
  (7, 65)	1
  (7, 0)	1
  (7, 38)	1
  (7, 63)	1
  (7, 91)	1
  (7, 3)	1
  (7, 6)	1
  (7, 14)	1
  (7, 96)	1
  (8, 77)	1
  (8, 5)	1
  (8, 86)	1
  (8, 7)	1
  (8, 80)	1
  (8, 28)	1
  (8, 13)	1
  (8, 24)	1
  (8, 49)	1
  (8, 93)	1
  (8, 30)	1
  (8, 37)	1
  (8, 95)	1


In [ ]:
cnt.vocabulary_

{'metaverse': 51,
 'is': 43,
 'network': 53,
 'of': 55,
 '3d': 2,
 'virtual': 94,
 'worlds': 98,
 'focused': 26,
 'on': 57,
 'social': 77,
 'connection': 15,
 'in': 35,
 'futurism': 29,
 'and': 5,
 'science': 71,
 'fiction': 25,
 'the': 86,
 'term': 84,
 'often': 56,
 'described': 18,
 'as': 7,
 'hypothetical': 34,
 'iteration': 44,
 'internet': 41,
 'single': 75,
 'universal': 88,
 'world': 97,
 'that': 85,
 'facilitated': 23,
 'by': 12,
 'use': 90,
 'augmented': 8,
 'reality': 68,
 'headsets': 33,
 'has': 31,
 'its': 46,
 'origins': 58,
 '1992': 1,
 'novel': 54,
 'snow': 76,
 'crash': 17,
 'portmanteau': 62,
 'meta': 50,
 'universe': 89,
 'various': 92,
 'metaverses': 52,
 'have': 32,
 'been': 9,
 'developed': 19,
 'for': 27,
 'popular': 61,
 'such': 81,
 'platforms': 60,
 'like': 48,
 'second': 72,
 'life': 47,
 'some': 78,
 'iterations': 45,
 'involve': 42,
 'integration': 39,
 'between': 10,
 'physical': 59,
 'spaces': 79,
 'economies': 21,
 'including': 36,
 'significant': 74,
 '

Q3) What is the token associated with word "metaverse"?

In [ ]:
cnt.vocabulary_['metaverse']

51

Q2) What is the shape of text_data after vectorization after the term that appeared in less than 2 documents are ignored?

In [ ]:
cnt1 = CountVectorizer(min_df=2)
Text_Count = cnt1.fit_transform(text_data)
Text_Count.shape

(9, 20)

Q4) Docs = ['This is the first question.', 'This document is the second document.', 'And this is the third one' ]
* Write a code to convert the above text into an array after tokenizing it using countvectorizer with 10 features. What will be the output?

In [ ]:
docs = ['This is the first question.', 'This document is the second document.', 'And this is the third one' ]
cnt2 = CountVectorizer(max_features=10)
docs_count = cnt2.fit_transform(docs)
print(docs_count.shape)
print(docs_count.toarray())

(3, 10)
[[0 0 1 1 0 1 0 1 0 1]
 [0 2 0 1 0 0 1 1 0 1]
 [1 0 0 1 1 0 0 1 1 1]]


Q5) Define a function called k_closest in python with the following signature:
* Which returns closest vectors in X which are closest to the vector p. Use the appropriate sklearn methods.
* Consider, X = np.asarray([[72, 69 ,82], [ 9 ,79, 99], [20 ,47, 88], [80 ,64, 49]]) p= np.asarray([[0,0,0]]) and k=1 For these values, what is the output of the function?

In [ ]:
import numpy as np 
from sklearn.neighbors import NearestNeighbors

def k_closest(X, p):
  knn = NearestNeighbors(n_neighbors=1)
  knn.fit(X)
  return knn.kneighbors(p)

X = np.asarray([[72, 69 ,82], [ 9 ,79, 99], [20 ,47, 88], [80 ,64, 49]]) 
p= np.asarray([[0,0,0]])
dist, indx = k_closest(X, p)
print(X[indx[0][0]])

[20 47 88]


Q6) Define a function called distance in python with the following signature: def distance( x0 : "A vector as np.array", X: "A list of vectors as np.ndarray", p : "p value for Minkowsky distance. Default 2, for Eucledian"):    which returns a list of calculated Minkowsky distances between the point x0 and all points in X. Recall that the p-Minkowsky distance between
$$  
x=(x1,x2,…xn)^T and \space y=(y1,y2,…yn)^T
$$
$$
δ(x,y) = (|x1−y1|^p+|x2−y2|^p+⋯+|xn−yn|^p)^{\frac{1}{p}}
​$$
Do not use any predefined function to calculate the same. 

Consider, X0 = np.array([1,0,0,0]), X= np.asarray([[1, 0, 0,0], [0, 1, 1,1],[1,2,0,0]]), p= 2 then, what is the output of the function distance(X0,X,p) ?

In [ ]:
def distance(x0, X, p=2):
  n = len(x0)
  dist = []
  for Xi in X:
    dist.append([])
    d = 0
    for i in range(n):
      d += (Xi[i] - x0[i])**p
    dist[-1].append(d**(1/p))
  return dist

X0 = np.array([1,0,0,0])
X = np.asarray([[1, 0, 0,0], [0, 1, 1,1],[1,2,0,0]])
p= 2
print(distance(X0, X, p))

[[0.0], [2.0], [2.0]]


Q7 to Q11
Load digit dataset on Colab (datasets.load_digits()) and use softmax regression to build the model Using following steps.
* Step 1: Load the dataset and split it using train_test_split by keeping: test_size= 0.2 random_state=10
* Step 2: Use standard scaler as a scaling function to scale the training as well as test data.
* Step 3: Use Logisticregression() as an estimator and set parameter (multi_class='multinomial', solver='sag') to predict the output.

In [ ]:
from sklearn.datasets import load_digits
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import ConfusionMatrixDisplay, classification_report

digits_data, digits_label = load_digits(return_X_y=True)
# type(digits_data)
X_train, X_test, y_train, y_test = train_test_split(digits_data, digits_label, test_size=0.2, random_state=10)
pipe = Pipeline([('scaler', StandardScaler()),
                 ('logreg', LogisticRegression(multi_class='multinomial', solver='sag'))
                 ])


Q7) What is the shape of features data you got in digits dataset ?

In [ ]:
digits_data.shape

(1797, 64)

Q8) How many labels are there in the dataset?

In [ ]:
len(np.unique(digits_label))

10

Q9) How many times label '7' is there in the dataset?

In [ ]:
len(digits_label[digits_label == 7])

179

Q 10) What is the accuracy of the trained model on test data?

In [ ]:
pipe.fit(X_train, y_train)
score = pipe.score(X_test, y_test)
print(score)
print(classification_report(y_test, pipe.predict(X_test)))

0.9666666666666667
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        37
           1       0.97      0.91      0.94        34
           2       0.89      1.00      0.94        34
           3       1.00      0.95      0.97        40
           4       1.00      0.94      0.97        34
           5       0.94      1.00      0.97        32
           6       0.97      0.97      0.97        37
           7       1.00      1.00      1.00        40
           8       0.89      0.94      0.91        33
           9       1.00      0.95      0.97        39

    accuracy                           0.97       360
   macro avg       0.97      0.97      0.97       360
weighted avg       0.97      0.97      0.97       360



Q11) Write the f1_score value you got .(Keep parameter average='weighted')

0.97

# Practice Assignment 7.2

Q1) Write a function compute_score(X_train, y_train, X_test, y_test)  to do the following on the Iris dataset-

Write your code keeping in mind:
* Split the Iris dataset into train and test set with 70:30 ratio
* Import svm.SVC as 'model'
* kernel as 'rbf', regularization parameter as 20 and gamma as 'auto'
* Take random_state=42

Train the model using trining data and predict the computed model's score using test data.
* Which of the following options is the computed score?

In [ ]:
from sklearn.svm import SVC

def compute_score(X_train, y_train, X_test, y_test):
  model = SVC(kernel='rbf', C=20, gamma='auto', random_state=42)
  model.fit(X_train, y_train)
  score = model.score(X_test, y_test)
  return score

In [ ]:
from sklearn.datasets import load_iris
import pandas as pd
from sklearn.model_selection import train_test_split
# iris_data, iris_label = load_iris(return_X_y=True)
#Define the column names
col_name=["sepal_length_in_cm", "sepal_width_in_cm","petal_length_in_cm","petal_width_in_cm", "class"]
#Read the dataset
df = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data", header = None, names= col_name)
# print(df.columns)
iris_data = df[df.columns[:-1]]
iris_label = df[df.columns[-1]]
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size=0.3, random_state=42)
score = compute_score(X_train, y_train, X_test, y_test)
print(score)

1.0


Q2) In 'Question 1', apply a pipeline containing a MinMaxScaler()function calledScaler and a svm.svc() called classifierwith the parameters : kernel='linear', decision_function_shape='ovr', C=1, class_weight=None. 

Calculate the precision value and f1 score and mark the correct option from the list below.

In [ ]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report
from sklearn.metrics import precision_score, recall_score, f1_score
pipe = Pipeline([('scaler', MinMaxScaler()),
                 ('svc', SVC(kernel='linear', decision_function_shape='ovr', C=1, class_weight=None))
                 ])
pipe.fit(X_train, y_train)
y_pred = pipe.predict(X_test)
cr = classification_report(y_test, y_pred)
print(cr)
precision = precision_score(y_test, y_pred, average=None)
print('Precision score: ', precision)
f1 = f1_score(y_test, y_pred, average=None)
print('F1 score: ', f1)

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        19
Iris-versicolor       1.00      1.00      1.00        13
 Iris-virginica       1.00      1.00      1.00        13

       accuracy                           1.00        45
      macro avg       1.00      1.00      1.00        45
   weighted avg       1.00      1.00      1.00        45

Precision score:  [1. 1. 1.]
F1 score:  [1. 1. 1.]


Q3) Import the iris dataset and drop the rows where class=Iris-versicolor. Apply a pipeline containing a MinMaxScaler()function calledScaler and a svm.svc() called classifier. Split the iris dataset into 50:50 ratio with random_state=0. Mark the correct recall value from the given options.

In [ ]:
import numpy as np
iris_new = iris_data[iris_label != 'Iris-versicolor']
label_new = iris_label[iris_label != 'Iris-versicolor']
iris_train, iris_test, label_train, label_test = train_test_split(iris_new, label_new, test_size=0.5, random_state=0)
np.unique(iris_label)
pipe1 = Pipeline([('Scaler', MinMaxScaler()),
                  ('classifier', SVC())
                  ])
pipe1.fit(iris_train, label_train)
y_pred1 = pipe1.predict(X_test)
recall = recall_score(y_test, y_pred, average='micro')
print(recall)

1.0


Q4) Write the function compute_score(X_train, y_train, X_test, y_test)
 to do the following on the Iris dataset-

Write your code keeping in mind:

* Split the Iris dataset into train and test set with 70:30 ratio and random_state=42
* Import sklearn.svm.LinearSVC as 'model'
* Consider loss function loss=hinge, random_state=42 and penalty=l2

Train the 'model' and mark the computed 'score'

In [ ]:
from sklearn.svm import LinearSVC
def compute_score(X_train, y_train, X_test, y_test):
  model = LinearSVC(loss='hinge', penalty='l2', random_state=42)
  model.fit(X_train, y_train)
  score = model.score(X_test, y_test)
  return score

In [ ]:
iris_data, iris_label = load_iris(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size=0.3, random_state=42)
score = compute_score(X_train, y_train, X_test, y_test)
print(score)

0.9777777777777777


Q5) Write a function hyperparameter_search which accepts the Kernel and regularization parameter as inputs and returns the avg_score of the models with the below mentioned hyperparameters.

* Split the Iris dataset into train and test set with 70:30 ratio
* kernels = ['linear', 'rbf']
* Regularization C = [5, 10,100]
* Cross Validation = 10
* random_state=42

Which of the following options give the accuracy_score for the iris dataset?

In [ ]:
from sklearn.model_selection import GridSearchCV
def hyperparameter_search(kernel, regularization):
  param_grid = dict(kernel=kernel, C=regularization)
  model = GridSearchCV(SVC(kernel = 'rbf'), scoring='accuracy', param_grid=param_grid, cv=10)
  model.fit(X_train, y_train) 
  best_est = model.best_estimator_
  print(best_est)
  score = best_est.score(X_test, y_test)
  print(score)

In [ ]:
iris_data, iris_label = load_iris(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size=0.3, random_state=42)
kernel = ['linear', 'rbf']
regularization = [5, 10,100]
hyperparameter_search(kernel, regularization)

SVC(C=5, kernel='linear')
0.9777777777777777


#Graded Assignment 7 (Part A)

Step 1: Download the dataset using following link: (https://drive.google.com/file/d/1v-uxWEgTI0GDCOTZOX3shUMkTf1a_CL7/view?usp=sharing)

Step 2: Import the data in google colab using pd.read_csv().

Step 3: Seperate features and target data in seperate variable X and Y.

Step 4: Convert dataframe X and series y into array and save it in variable X_array,y_array.

Step 5: Split the dataset using train_test_split. (Keep parameter train_size=0.7 and random_state=10).

Step 6: Reshape the dataset in such a way that each entry of data has 90 samples.

Step 7: Use SGD regressor as an estimator and partial_fit to fit the dataset on the model. (Set random_state=10)

Step 8: Calculate different evaluation metrics value like mean_square_error, R2_score.

Use the training set for fitting the model and use the test data to make the predictions.

Note: No need to scale the data. It's already scaled.

Answer the below questions.

In [ ]:
from tables.flavor import toarray
df = pd.read_csv('/content/sample_data/data_for_large_scale.csv')
# df = pd.read_csv('https://drive.google.com/file/d/1v-uxWEgTI0GDCOTZOX3shUMkTf1a_CL7/view?usp=sharing')
X, y = df[df.columns[:-1]], df[df.columns[-1]]
X_array, y_array = X.to_numpy(), y.to_numpy()
print(X_array.shape, y_array.shape)
X_train, X_test, y_train, y_test = train_test_split(X_array, y_array, test_size=0.3, random_state=10)
print(X_train.shape)
X_train, X_test, y_train, y_test = X_train.reshape(-1,90,10), X_test.reshape(-1,90,10), y_train.reshape(-1,90,1), y_test.reshape(-1,90,1)
print(X_train.shape, y_train.shape, X_test.shape, y_test.shape)

(90000, 10) (90000,)
(63000, 10)
(700, 90, 10) (700, 90, 1) (300, 90, 10) (300, 90, 1)


In [ ]:
from sklearn.linear_model import SGDRegressor
sgd = SGDRegressor(random_state=10)
coef = []
for iter in range(X_train.shape[0]):
  # Need to pass the classes in the first iteration, since it's not guaranteed to have the same classes in all chunks of data.
  if iter == 0:
    # sgd.partial_fit(X_train[iter, :, :], y_train[iter, :, :], classes=np.unique(y))
    sgd.partial_fit(X_train[iter, :, :], y_train[iter, :, :])
  else:
    sgd.partial_fit(X_train[iter, :, :], y_train[iter, :, :])
  coef.append(sgd.coef_)

  # print(f'After iteration #{iter}, coef_ is {sgd.coef_}, intercept+ is {sgd.intercept_}')

print(sgd.intercept_)

[-0.0054532]


Q3) What is the value of cofficient corresponding to "feature-3"you got after trainig the model using SGDRegressor? (select the closest answer)

In [ ]:
print(sgd.coef_)

[51.3212522  22.26535893 81.23762868 53.19615839 76.46565732 71.47204651
 93.45092409 51.92198178 30.03910055 40.95656774]


Q4) What is the value of R2 score for test data

In [ ]:
from sklearn.metrics import r2_score
y_pred = sgd.predict(X_test.reshape(-1,10))
score = r2_score(y_test.reshape(-1,1), y_pred)
print(score)

0.9999919793766233


Q5) What is the value of cofficient corresponding to "feature-5" after 5th iteration.

In [ ]:
coef[4]

array([51.3212522 , 22.26535893, 81.23762868, 53.19615839, 76.46565732,
       71.47204651, 93.45092409, 51.92198178, 30.03910055, 40.95656774])

Q 6-8)

This dataset was constructed by adding elevation information to a 2D road network in North Jutland, Denmark (covering a region of 185 x 135 km^2). Elevation values where extracted from a publicly available massive Laser Scan Point Cloud for Denmark. This 3D road network was eventually used for benchmarking various fuel and CO2 estimation algorithms. This dataset can be used by any applications that require to know very accurate elevation information of a road network to perform more accurate routing for eco-routing, cyclist routes etc. For the data mining and machine learning community, this dataset can be used as 'ground-truth' validation in spatial mining techniques and satellite image processing. It has no class labels,

Use this dataset to guess some missing elevation information for some points on the road.

Column names:

OSM_ID: OpenStreetMap ID for each road segment or edge in the graph.

LONGITUDE: Web Mercaptor (Google format) longitude

LATITUDE: Web Mercaptor (Google format) latitude

ALTITUDE: Height in meters.

Load the dataset from link("https://archive.ics.uci.edu/ml/machine-learning-databases/00246/3D_spatial_network.txt"). Set parameter chunk size=20000 and iterator =True in pd.read_csv().

NOTE: The above file doesn't have column names

Scale your whole dataset first with standard scalar using partial_fit method. Then use SGDRegressor(random state=10) on the dataset and answer the following.

In [ ]:
# from sklearn.preprocessing import StandardScaler
# ss = StandardScaler()
# sgdreg = SGDRegressor(random_state=10, warm_start=True)
# # data = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/00246/3D_spatial_network.txt',chunksize=20000,iterator=True, header=None, names=['OSM_ID', 'LONGITUDE', 'LATITUDE', 'ALTITUDE'])
# iter = 1
# coef = []
# intercept = []
# size = 0
# for train_df in pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/00246/3D_spatial_network.txt',chunksize=20000,iterator=True, header=None, names=['OSM_ID', 'LONGITUDE', 'LATITUDE', 'ALTITUDE']):
#   ss.partial_fit(train_df)
#   train_df_scaled = ss.transform(train_df)
#   # print(f"Partial scaled output is: {train_df_scaled}")
  
#   X_train_partial = train_df_scaled[:, 0:3]  # since there are 3 features in dataset
#   y_train_partial = train_df_scaled[:, 3] # last column is the label
#   size += X_train_partial.shape[0]
#   sgdreg.partial_fit(X_train_partial, y_train_partial)
#   sgdreg.partial_fit(X_train_partial, y_train_partial)
#   coef.append(sgdreg.coef_)
#   intercept.append(sgdreg.intercept_)
#   iter += 1

In [ ]:
ss = StandardScaler()
sgdreg = SGDRegressor(random_state=10)
chunksize=20000
intercept = []
coef = []
iter = 1
size = 0

for train_df in pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/00246/3D_spatial_network.txt', header=None, names=['OSM_ID', 'LONGITUDE', 'LATITUDE', 'ALTITUDE'], chunksize=chunksize, iterator=True):
  ss.partial_fit(train_df)

for train_df in pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/00246/3D_spatial_network.txt', header=None, names=['OSM_ID', 'LONGITUDE', 'LATITUDE', 'ALTITUDE'], chunksize=chunksize, iterator=True):
  train_df_scaled = ss.transform(train_df)
  
  X_train_partial = train_df_scaled[:, 1:3]  # exclude 0 which is ID column. columns 1 and 2 are features
  # y_train_partial = train_df_scaled[:, 3] # last column is the label
  y_train_partial = train_df[train_df.columns[-1]]
  size += X_train_partial.shape[0]
  sgdreg.partial_fit(X_train_partial, y_train_partial)
  coef.append(sgdreg.coef_)
  intercept.append(sgdreg.intercept_)
  if(iter==7):
    print('After iterations #: ', iter)
    print(sgdreg.coef_)
    print(sgdreg.intercept_)
  iter += 1
print(iter)

After iterations #:  7
[ 4.7924744  -5.10625804]
[21.39333846]
23


Q6) Check how many total samples are there in the dataset?

In [ ]:
size

434874

Q7) What is the value of intercept after 7th iteration. (select the closest option).

In [ ]:
intercept[:7]

[array([24.44543684]),
 array([21.27380942]),
 array([23.94764565]),
 array([21.56160507]),
 array([21.63953089]),
 array([20.54946551]),
 array([21.39333846])]

Q8) What is the value of the coefficient corresponding to the longitude feature after the 7th iteration? (select the closest option).

In [ ]:
coef[:10]

[array([ 3.0938621 , -5.22002704]),
 array([ 3.0938621 , -5.22002704]),
 array([ 3.0938621 , -5.22002704]),
 array([ 3.0938621 , -5.22002704]),
 array([ 3.0938621 , -5.22002704]),
 array([ 3.0938621 , -5.22002704]),
 array([ 3.0938621 , -5.22002704]),
 array([ 3.0938621 , -5.22002704]),
 array([ 3.0938621 , -5.22002704]),
 array([ 3.0938621 , -5.22002704])]

Q 9 - 11
Load Iris datset on Colab and use KNN classifier to build the model Using following steps.
* Step 1: Load the dataset and split it using train_test_split by keeping: test_size= 0.2 random_state=10
* Step 2: Use Normalizer() as a scaling function to scale the data.
* Step 3: Use KNeighborsClassifier(K) as an estimator to predict the output.

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import Normalizer
iris_data, iris_label = load_iris(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size=0.2, random_state=10)
pipe_knn = Pipeline([('scaler', Normalizer()),
                     ('knn', KNeighborsClassifier(n_neighbors=1))
                     ])
gcv = GridSearchCV(pipe_knn, param_grid={'knn__n_neighbors': [2,3,4]}, scoring='accuracy', n_jobs=1)
gcv.fit(X_train, y_train)
gcv.best_estimator_

Pipeline(steps=[('scaler', Normalizer()),
                ('knn', KNeighborsClassifier(n_neighbors=3))])

In [ ]:
gcv.best_score_

0.9666666666666668

In [ ]:
f1 = f1_score(y_test, gcv.best_estimator_.predict(X_test), average='weighted')
print(f1)

0.9671111111111111


#Graded Assignment - 7 (PART - B)
Q1) Write a function compute_GridSearchCV which accepts the Kernel and regularization parameters as inputs and returns the Mean cross-validated score of the best_estimator, denoted with best_score_ of the models with the below-mentioned hyperparameters:
Split the Iris dataset into train and test sets with 70:30 ratio
Import svm.SVC as 'model'
kernels = ['linear' , 'rbf']
Regularization = [1,15,25]
gamma = 'auto'
Cross Validation = 4
random_state=0
Note: Mark the closest option.

In [ ]:
from sklearn.svm import SVC
from sklearn.datasets import load_iris
from sklearn.model_selection import GridSearchCV

iris_data, iris_label = load_iris(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(iris_data, iris_label, test_size=0.3, random_state=0)

pipe_svc = Pipeline([('svc', SVC(gamma='auto', random_state=0))
                     ])
param_grid={'svc__kernel': ['linear', 'rbf'],
            'svc__C': [1, 15, 25]            
            }
gcv = GridSearchCV(pipe_svc, param_grid=param_grid, cv=4, return_train_score=True)
gcv.fit(X_train, y_train)
gcv.best_estimator_
print('Mean of the score of best estimator: ', gcv.best_estimator_.score(X_train, y_train).mean())
print('Mean training score: ', gcv.cv_results_['mean_train_score'].mean())
print('Mean test score: ', gcv.cv_results_['mean_test_score'].mean())

Mean of the score of best estimator:  0.9809523809523809
Mean training score:  0.9883425294817699
Mean test score:  0.9541191832858501


Q2 and Q3
Read the instructions given below to answer the two questions given below.

Split the Social_Network_Ads dataset
(https://drive.google.com/file/d/1qUa1GlG4X4ZY_4E0e7jPR-z7AG7NIDbE/view?usp=sharing) into training and test set in 75:25 ratio.

Fit and transform the train and test set of the feature matrix by applying StandardScaler transformer.

Fit a linear SVM (with random_state = 0and linear kernel) to training data.

In [ ]:
from sklearn.metrics import accuracy_score
sna_dataset = pd.read_csv('/content/sample_data/Social_Network_Ads.csv')
# print(sna_dataset.head())
X = sna_dataset.drop(columns='Purchased')
y = sna_dataset['Purchased']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)
pipe = Pipeline([('scaler', StandardScaler()),
                 ('svc', SVC(kernel='linear', random_state=0) )
                 ])
pipe.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('svc', SVC(kernel='linear', random_state=0))])

Q2) The predicted data returns an accuracy_score on test data. Which of the following option represents the calculated accuracy_score?

In [ ]:
y_pred = pipe.predict(X_test)
acc = accuracy_score(y_test, y_pred)
print('Accuracy score: ', acc)

Accuracy score:  0.9


Q3) Calculate the confusion matrix obtained from the above-predicted data.

In [ ]:
from sklearn.metrics._plot.confusion_matrix import confusion_matrix
print(confusion_matrix(y_test, y_pred))

[[66  2]
 [ 8 24]]


From the MNIST dataset, consider the first 20,000 data samples as training data and the next 5,000 data samples as test data. Fit a pipeline with MinMaxScaler and a classifier with SVC, linear kernel, one vs rest decision_function_shape and class_weight=None to this dataset and answer the following questions(Q.no 4 and Q.no 5).

In [ ]:
from sklearn.datasets import fetch_openml
X, y = fetch_openml('mnist_784', version=1, return_X_y=True)
X_train, X_test, y_train, y_test = X[:20000], X[20000:25000], y[:20000], y[20000:25000]
pipe = Pipeline([('scaler', MinMaxScaler()),
                 ('svc', SVC(kernel='linear', decision_function_shape='ovr', class_weight=None))
                 ])
pipe.fit(X_train, y_train)

KeyboardInterrupt: ignored

In [ ]:
y_pred = pipe.predict(X_test)
cm = confusion_matrix(y_test, y_pred)

Q4) What is the sum of the main diagonal elements of the confusion matrix?

In [ ]:
cm.diagonal().sum()

Q5) Which of the following are the correct values of precision, recall and f1_Score?

In [ ]:
print(classification_report(y_test, y_pred))

Q6) Consider the MNIST dataset, split it into training and test set in 50:50 ratio with random_state = 42. 
* Fit a SVM model using pipeline with StandardScalar, SVM classifier kernel='poly' and degree = 3, decision_function_shape='ovr'and class_weight='balanced', C=10. 
* Train the model on training data, and make predictions for test data.
* Generate the Classification report and choose the correct value for weighted avg of f1_score.

In [ ]:
# from sklearn.datasets import fetch_openml
# X, y = fetch_openml('mnist_784', version=1, return_X_y=True)
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=42)
# pipe = Pipeline([('scaler', StandardScaler()),
#                  ('svc', SVC(kernel='poly', degree=3, decision_function_shape='ovr', class_weight='balanced', C=10))
#                  ])
# pipe.fit(X_train, y_train)
# y_pred = pipe.predict(X_test)
# print(classification_report(y_test, y_pred))

Q7) Write the function compute_score(X_train, y_train, X_test, y_test) to do the following on the Iris dataset-

Write your code keeping in mind:
* Split the Iris dataset into train and test set with 70:30 ratio
* Import svm.SVC as 'model' kernel as 'poly', regularization parameter as 10 and gamma as 'auto'
* Train the 'model' and mark the computed 'score'
* Train the model and mark the computed accuracy score for test data.

In [ ]:
from sklearn.datasets import load_iris
X, y = load_iris(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
svc = SVC(kernel='poly', C=10, gamma='auto')
svc.fit(X_test, y_test)
train_score = svc.score(X_train, y_train)
test_score = svc.score(X_test, y_test)
print('Train score: ', train_score)
print('Tesrt score: ', test_score)
print('Accuracy score: ', accuracy_score(y_test, svc.predict(X_test)))

Q8) Write the function compute_score(X_train, y_train, X_test, y_test) to do the following on the Iris dataset-

Write your code keeping in mind the following:
* Split the Iris dataset into train and test sets with 70:30 ratio
* Import svm.SVC as 'model', kernel as 'sigmoid', regularization parameter as 25, and gamma as 'auto'
* Train the 'model' and mark the computed 'accuracy score' for the test data.'

In [ ]:
from sklearn.datasets import load_iris
X, y = load_iris(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
svc = SVC(kernel='sigmoid', C=25, gamma='auto')
svc.fit(X_train, y_train)
train_score = svc.score(X_train, y_train)
test_score = svc.score(X_test, y_test)
print('Train score: ', train_score)
print('Tesrt score: ', test_score)
print('Accuracy score: ', accuracy_score(y_test, svc.predict(X_test)))

Q9) Import the iris dataset and drop the rows where class=Iris-setosa. Apply a pipeline containing a MinMaxScaler()function calledScaler and a svm.svc() called classifier. Split the iris dataset into 75:25 ratio with random_state=0. Mark the correct precision score.

In [ ]:
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import precision_score, classification_report
from sklearn.datasets import load_iris
X, y = load_iris(return_X_y=True)
X, y = X[np.where(y!=0)], y[np.where(y!=0)]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)
pipe = Pipeline([('scaler', MinMaxScaler()),
                 ('svc', SVC())
                 ])
pipe.fit(X_train, y_train)
y_pred = pipe.predict(X_test)
score = precision_score(y_test, y_pred)
print('Precision Score: ', score)
print(classification_report(y_test, y_pred))